### ISSUE TITLE
회원가입 시 비밀번호 조건

### ISSUE THREAD

**Issue by bellmin1** [kookmin-sw/2018-cap1-10#16]
회원가입 시 비밀번호 조건을 어떻게 할 것인지 의견 부탁드립니다.

예 : 10~15자, 영문 대소문자, 숫자, 특수문자 포함

**Comment by YOUNGRANGCHO** [comment]
특수문자는 안하고 영문,숫자까지만 해도 좋을거 같아요~
8자부터 되는 것도 좋을거 같아요~

**Comment by bellmin1** [comment]
저도 찬성입니다.
영문 대소문자, 숫자 포함 8자 이상

**Comment by bellmin1** [comment]
다른 의견이 없는것 같으므로 "영문 대소문자, 숫자 포함 8자 이상"로 결정합니다. 모든 팀원들은 숙지하시기 바랍니다.
