### ISSUE TITLE
주간 지도교수 상담시간 결정

### ISSUE THREAD

**Issue by bellmin1** [kookmin-sw/2018-cap1-10#3]
각 팀원들은 가능 시간대 (예 : 월 17시 이후, 화 10시-13시 등) 를 적어 게시해주시기 바랍니다.

최종 종합하여 정한 후 지도교수님께 전달할 예정입니다.

**Comment by YOUNGRANGCHO** [comment]
월 점심, 6시 이후
화 6시 이후
수 점심, 6시 이후
목 점심, 4시-6시
금 7시 이후

**Comment by bellmin1** [comment]
월 15시이후
화 종일
수 15시 이후
목 13시 이후

**Comment by Hyeong-u** [comment]
화요일 6시 이후가 좋습니다.

**Comment by kwc2013** [comment]
화요일 6시 이후 찬성입니다.

**Comment by bellmin1** [comment]
@Hyeong-u  @kwc2013    혹시 다른 날은 가능 날짜 있나요? 화요일은 제가 간헐적으로만 될 것 같습니다..

**Comment by Hyeong-u** [comment]
@bellmin1  수요일 저녁도 괜찮긴 한데 UROP 진행으로 학기 중에 세 번정도는 불가능할 수 있습니다.

**Comment by bellmin1** [comment]
일단 수요일 18시 이후로 하겠습니다. 아무래도 팀장이 가끔 빠지는것보다는 이것이 최선일 것 같습니다..

**Comment by bellmin1** [comment]
@YOUNGRANGCHO @Hyeong-u @kwc2013  수요일 18시로 정할까 합니다.. 가능하면 가능하다고 코멘트 해주시기 바랍니다~

**Comment by kwc2013** [comment]
화목금 학교를 늦게까지 있기 때문에 월, 수는 피하면 좋겠습니다.

**Comment by bellmin1** [comment]
서로 저녁시간이 맞지 않아 점심시간으로 정해야 할 것 같습니다. 가능 점심시간을 다시 말씀해주시기 바랍니다. 저는 월, 화, 수, 금 가능합니다.

**Comment by bellmin1** [comment]
@YOUNGRANGCHO @Hyeong-u @kwc2013

**Comment by Hyeong-u** [comment]
점심시간이 12시부터 1시 사이라면 화목 가능합니다.

**Comment by kmu-yoonsh** [comment]
^^ 그냥 모니터링 하다가 잠시 남기고 갑니다. 

시간표를 모두 코멘트로 남긴 것은 좋은 것 같습니다. 그런데 협의를 위한 대화까지 남기기 시작하면.. 나중에는 정보가 과도하게 남겨지고 유의미한 정보를 판별하는 시간이 소용될거 같네요. 참고하세요.

**Comment by bellmin1** [comment]
@kmu-yoonsh  조언 감사합니다. 참고하도록 하겠습니다.

**Comment by bellmin1** [comment]
목요일 점심으로 결정
