### ISSUE TITLE
수행계획서 웹부분 작성

### ISSUE THREAD

**Issue by Hyeong-u** [kookmin-sw/2018-cap1-10#5]
웹 부분에서 우리가 달성해야할 목표들을 코멘트로 적어서 문서화 시키고자 합니다.
생각나는대로 코멘트 적어주세요.

**Comment by Hyeong-u** [comment]
회원.OAuth연동(구글, 페이스북) / 회원.쪽지 / 회원.이용약관 / 회원.탈퇴

**Comment by Hyeong-u** [comment]
게시판은 기본적은 구조가 갖춰지면 위지위그 에디터를 도입하는게 어떨까 생각하는데 팀원들의 의견이 궁금합니다. 제가 찾아본 에디터는 다음 링크입니다.
https://summernote.org/
간단한 소개글: http://yeolsimlog.net/17

**Comment by Hyeong-u** [comment]
서버구축.nginx설정 / 서버구축.uwsgi설정 / 서버구축.도메인연결 / 서버구축.데이터베이스인스턴스생성

**Comment by YOUNGRANGCHO** [comment]
올려주신 에디터 무난하고 괜찮은거 같아요.

**Comment by YOUNGRANGCHO** [comment]
게시판 목록형, 앨범형 만들기 / 글마다 추천기능 만들기

**Comment by YOUNGRANGCHO** [comment]
회원가입과 메인페이지 요청사항 수정 / 요청사항 수정,   CSS 작업

**Comment by kwc2013** [comment]
게시판 구축 / 게시글 작성 / 수정 / 삭제
