### ISSUE TITLE
소개 영상 제작에 관한 의견

### ISSUE THREAD

**Issue by bellmin1** [kookmin-sw/2018-cap1-10#6]
README.md에 소개 영상이 들어가야 합니다.

간단하게 제작하면 될듯 한데 어떤 방식이 좋을지 각자 의견 추가 부탁드립니다.

**Comment by Hyeong-u** [comment]
계획서 슬라이드 쇼가 작성이 되면 해당 슬라이드 쇼를 동영상으로 변환하여 유튜브에 업로드 후 링크를 걸면 될 것 같습니다.

**Comment by YOUNGRANGCHO** [comment]
소개 내용은 구글 드라이브 문서에 회의기록 다 남겨놨으니까 그거 그대로 사용하면 될거같아요
금요일 전에 만나서 녹음도 분량 나눠서 같이 하는게 좋을까요??

**Comment by bellmin1** [comment]
음.. 분량을 나누는것도 좋고.. 너무 조잡하다 싶으면 대본을 잘 만들어서 한사람이 쭉 하는것도 좋구요.. 여러 방법이 있지요~
